#!/usr/bin/env python3
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Writes an empty valid image for builds that do not have recorded artifacts. An
# image with no artifacts causes the runtime to generate code normally.

import struct
import sys

# Keep these constants synchronized with the image format.
IMAGE_MAGIC = 0x49544F41  # "AOTI"
IMAGE_VERSION = 3
FINGERPRINT_SIZE = 20
ALIGNMENT = 16
TEXT_ALIGNMENT = 4096
HEADER_FMT = "<IHHIIIIIII"
HEADER_SIZE = struct.calcsize(HEADER_FMT)
assert HEADER_SIZE == 36


def align_up(v, a):
    return (v + a - 1) & ~(a - 1)


def empty_image():
    fingerprint_offset = HEADER_SIZE
    directory_offset = align_up(fingerprint_offset + FINGERPRINT_SIZE, ALIGNMENT)
    data_end = directory_offset  # no entries, no data
    text_offset = align_up(data_end, TEXT_ALIGNMENT)
    text_size = 0
    image_size = text_offset

    buf = bytearray(image_size)
    struct.pack_into(
        HEADER_FMT,
        buf,
        0,
        IMAGE_MAGIC,
        IMAGE_VERSION,
        0,
        0,  # blobCount
        fingerprint_offset,
        FINGERPRINT_SIZE,
        directory_offset,
        text_offset,
        text_size,
        image_size,
    )
    # A zero fingerprint marks an empty image.
    return bytes(buf)


def main(output):
    output.write(empty_image())
    return 0


# A zero slot table hash tells the shim there is nothing to check.
def main_relocs(output):
    lines = [
        "// Generated by GenerateEmptyAOTImage.py. Do not edit.",
        "AOT_IMAGE_SLOT_TABLE_HASH(0x00000000u)",
        f"AOT_IMAGE_CHUNK(0, {len(empty_image())})",
    ]
    output.write("\n".join(lines).encode() + b"\n")
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("usage: GenerateEmptyAOTImage.py IMAGE RELOCS", file=sys.stderr)
        sys.exit(1)
    with open(sys.argv[1], "wb") as f:
        main(f)
    with open(sys.argv[2], "wb") as f:
        main_relocs(f)
